import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { IdeType } from '../types.js';


const CODEX_MCP_SECTION_HEADER = '[mcp_servers.ai-memory]';
const CODEX_MCP_SECTION = `\n${CODEX_MCP_SECTION_HEADER}\ncommand = "ai-memory"\nargs = ["mcp"]\n`;

// Registers MCP server for Cursor (writes to mcp.json)
export function registerCursorMcp(mcpFilePath: string): { updated: boolean } {
  const dir = dirname(mcpFilePath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  let mcpData: any = {};
  if (existsSync(mcpFilePath)) {
    mcpData = JSON.parse(readFileSync(mcpFilePath, 'utf8'));
  }
  mcpData.mcpServers ??= {};
  if (mcpData.mcpServers['ai-memory']) return { updated: false };
  mcpData.mcpServers['ai-memory'] = { command: 'ai-memory', args: ['mcp'] };
  writeFileSync(mcpFilePath, JSON.stringify(mcpData, null, 2));
  return { updated: true };
}

// Registers MCP server for Claude Code (writes mcpServers to settings.json)
export function registerClaudeCodeMcp(settingsFilePath: string): { updated: boolean } {
  const dir = dirname(settingsFilePath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  let data: any = {};
  if (existsSync(settingsFilePath)) {
    data = JSON.parse(readFileSync(settingsFilePath, 'utf8'));
  }
  data.mcpServers ??= {};
  if (data.mcpServers['ai-memory']) return { updated: false };
  data.mcpServers['ai-memory'] = { command: 'ai-memory', args: ['mcp'] };
  writeFileSync(settingsFilePath, JSON.stringify(data, null, 2));
  return { updated: true };
}

// Registers MCP server for Codex (writes [mcp_servers.ai-memory] to config.toml)
export function registerCodexMcp(configPath: string): { status: 'created' | 'updated' | 'exists' } {
  const dir = dirname(configPath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  let content = '';
  const fileExisted = existsSync(configPath);
  if (fileExisted) {
    content = readFileSync(configPath, 'utf8');
  }

  if (content.includes(CODEX_MCP_SECTION_HEADER)) {
    return { status: 'exists' };
  }

  content = content.trimEnd() + '\n' + CODEX_MCP_SECTION;
  writeFileSync(configPath, content);
  return { status: fileExisted ? 'updated' : 'created' };
}

// D040: Skill definitions — user-triggered slash commands generated by `ai-memory init`
export const SKILL_DEFINITIONS: Record<string, string> = {
  'ai-memory-status': `---
name: ai-memory-status
description: Quick health check — conversation count, turn count, tool usage stats
disable-model-invocation: true
---
Call the ai-memory-status tool and present the results as a brief, readable summary.
Show conversation count, turn count, DB path, and tool usage stats.
`,
  'ai-memory-search': `---
name: ai-memory-search
description: Search conversation history by keyword
argument-hint: "[query]"
disable-model-invocation: true
---
Search ai-memory for: $ARGUMENTS

Call ai-memory-search with the query and present results showing conversation titles, dates, and matching snippets.
`,
  'ai-memory-recent': `---
name: ai-memory-recent
description: Recent conversations — titles, summaries, dates
disable-model-invocation: true
---
Call ai-memory-conversations with limit 10 and present the results as a readable list.
Show title, date, and summary for each conversation.
`,
  'ai-memory-summarize': `---
name: ai-memory-summarize
description: Summarize this conversation and save it via ai-memory
disable-model-invocation: true
---
Summarize this conversation and save it to ai-memory:
1. Call ai-memory-conversations (limit 5) to find the current conversation by matching the title or most recent timestamp.
2. Write a progressive summary: start with a one-line overview, then key decisions and open items. Be specific — include names, choices, and reasoning.
3. Write a concise title (~60 chars) that reflects the current topic.
4. Call ai-memory-summarize with the conversation_id, your summary text, and the title.
`,
};

function ideSkillsDir(ide: IdeType, home: string): string {
  // Codex reads user skills from ~/.agents/skills/ (Agent Skills standard), not ~/.codex/skills/
  if (ide === 'codex') return join(home, '.agents', 'skills');
  const ideDir = ide === 'claude-code' ? '.claude' : '.cursor';
  return join(home, ideDir, 'skills');
}

export function writeSkills(ide: IdeType, home: string): { written: string[]; skipped: string[] } {
  const baseDir = ideSkillsDir(ide, home);
  const written: string[] = [];
  const skipped: string[] = [];

  for (const [name, content] of Object.entries(SKILL_DEFINITIONS)) {
    const dir = join(baseDir, name);
    const file = join(dir, 'SKILL.md');
    mkdirSync(dir, { recursive: true });

    if (existsSync(file) && readFileSync(file, 'utf8') === content) {
      skipped.push(name);
    } else {
      writeFileSync(file, content);
      written.push(name);
    }
  }

  return { written, skipped };
}
