import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { createToolHandlers } from './server.js';

export async function startStdioServer(dbPath: string) {
  const server = new McpServer({ name: 'ai-memory', version: '0.2.0' });
  const handlers = createToolHandlers(dbPath);

  server.tool(
    'ai-memory-search',
    'Search conversation history. Returns matching conversations with turn snippets. Use this when you need past context.',
    {
      query: z.string().optional().describe('Search query text'),
      workspace: z.string().nullable().optional().describe('Filter by workspace name'),
      date_from: z.string().optional().describe('ISO date lower bound (filters on updated_at)'),
      date_to: z.string().optional().describe('ISO date upper bound (filters on updated_at)'),
      role: z.enum(['user', 'assistant']).optional().describe('Filter by turn role'),
      limit: z.number().optional().describe('Max number of results (default 20)'),
      offset: z.number().optional().describe('Pagination offset')
    },
    async (input) => {
      try {
        const result = await handlers['ai-memory-search'](input);
        return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
      } catch (e: any) {
        return { content: [{ type: 'text' as const, text: JSON.stringify({ error: e.message }) }], isError: true };
      }
    }
  );

  server.tool(
    'ai-memory-conversations',
    'List recent conversations with title and summary.',
    {
      workspace: z.string().nullable().optional().describe('Workspace name'),
      date_from: z.string().optional().describe('ISO date lower bound (filters on updated_at)'),
      date_to: z.string().optional().describe('ISO date upper bound (filters on updated_at)'),
      limit: z.number().optional().describe('Max results (default 20)'),
      offset: z.number().optional().describe('Pagination offset')
    },
    async (input) => {
      try {
        const result = await handlers['ai-memory-conversations'](input);
        return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
      } catch (e: any) {
        return { content: [{ type: 'text' as const, text: JSON.stringify({ error: e.message }) }], isError: true };
      }
    }
  );

  server.tool(
    'ai-memory-conversation',
    'Get full transcript for a conversation.',
    {
      conversation_id: z.string().describe('Conversation ID')
    },
    async (input) => {
      try {
        const result = await handlers['ai-memory-conversation'](input);
        return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
      } catch (e: any) {
        return { content: [{ type: 'text' as const, text: JSON.stringify({ error: e.message }) }], isError: true };
      }
    }
  );

  server.tool(
    'ai-memory-summarize',
    'Update the summary for the current conversation. Call after important progress — decisions made, direction changes, milestones reached, or when the user asks. Start with a one-line overview, then add key decisions and open items. Be specific — include names, choices, and reasoning. Optionally include title (~60 chars) when the topic is clear or changed.',
    {
      conversation_id: z.string().describe('Conversation ID'),
      summary: z.string().describe('Progressive summary text'),
      title: z.string().optional().describe('Optional concise title (~60 chars) when topic is clear or changed')
    },
    async (input) => {
      try {
        const result = await handlers['ai-memory-summarize'](input);
        return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
      } catch (e: any) {
        return { content: [{ type: 'text' as const, text: JSON.stringify({ error: e.message }) }], isError: true };
      }
    }
  );

  server.tool(
    'ai-memory-status',
    'Health check — shows conversations count, turns count, DB path, and index status.',
    {
      workspace: z.string().nullable().optional().describe('Filter by workspace')
    },
    async (input) => {
      try {
        const result = await handlers['ai-memory-status'](input);
        return { content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }] };
      } catch (e: any) {
        return { content: [{ type: 'text' as const, text: JSON.stringify({ error: e.message }) }], isError: true };
      }
    }
  );

  // D040: MCP prompts removed — replaced by IDE skill files (generated by `ai-memory init`)

  const transport = new StdioServerTransport();
  await server.connect(transport);
}
