// D046: Skill definitions — user-triggered slash commands generated by `ai-memory init`
// Each value is the full SKILL.md content (YAML frontmatter + body) written to ~/.<ide>/skills/<name>/SKILL.md

export const SKILL_DEFINITIONS: Record<string, string> = {
  'ai-memory-status': `---
name: ai-memory-status
description: Quick health check — conversation count, turn count, tool usage stats
disable-model-invocation: true
---
Call the ai-memory-status tool and present the results as a brief, readable summary.
Show conversation count, turn count, DB path, and tool usage stats.
`,
  'ai-memory-search': `---
name: ai-memory-search
description: Search conversation history by keyword
argument-hint: "[query]"
disable-model-invocation: true
---
Search ai-memory for: $ARGUMENTS

Call ai-memory-search with the query and present results showing conversation titles, dates, and matching snippets.
`,
  'ai-memory-recent': `---
name: ai-memory-recent
description: Recent conversations — titles, summaries, dates
disable-model-invocation: true
---
Call ai-memory-conversations with limit 10 and present the results as a readable list.
Show title, date, and summary for each conversation.
`,
  'ai-memory-summarize': `---
name: ai-memory-summarize
description: Summarize this conversation and save it via ai-memory
disable-model-invocation: true
---
Summarize this conversation and save it to ai-memory:
1. Call ai-memory-conversations (limit 5) to find the current conversation by matching the title or most recent timestamp.
2. Write a progressive summary: start with a one-line overview, then key decisions and open items. Be specific — include names, choices, and reasoning.
3. Write a concise title (~60 chars) that reflects the current topic.
4. Call ai-memory-summarize with the conversation_id, your summary text, and the title.
`,
};
