import { describe, expect, test } from 'vitest';
import { stripPromptWrappers } from '../../src/utils/strip.js';

describe('stripPromptWrappers', () => {
  test('strips <user_query> wrapper', () => {
    expect(stripPromptWrappers('<user_query>\nHello world\n</user_query>')).toBe('Hello world');
  });

  test('strips <user_query> with attributes', () => {
    expect(stripPromptWrappers('<user_query type="chat">\nHello\n</user_query>')).toBe('Hello');
  });

  test('strips <user_message> wrapper', () => {
    expect(stripPromptWrappers('<user_message>\nSome text\n</user_message>')).toBe('Some text');
  });

  test('removes entire <ide_opened_file> noise block', () => {
    const input = '<ide_opened_file>The user opened the file /path/to/file.ts in the IDE.</ide_opened_file>';
    expect(stripPromptWrappers(input)).toBe('');
  });

  test('removes entire <local-command-caveat> noise block', () => {
    const input = '<local-command-caveat>Caveat: The messages below were generated by the user.</local-command-caveat>';
    expect(stripPromptWrappers(input)).toBe('');
  });

  test('strips noise block prefix then extracts user_query content', () => {
    const input = '<ide_opened_file>opened file</ide_opened_file>\n<user_query>\nDo something\n</user_query>';
    expect(stripPromptWrappers(input)).toBe('Do something');
  });

  test('leaves plain text unchanged', () => {
    expect(stripPromptWrappers('Just a normal prompt')).toBe('Just a normal prompt');
  });

  test('preserves inner XML-like content', () => {
    const input = '<user_query>\nCheck the <div> element\n</user_query>';
    expect(stripPromptWrappers(input)).toBe('Check the <div> element');
  });

  test('only strips known wrappers', () => {
    expect(stripPromptWrappers('<user_query>\n<unknown>inner</unknown>\n</user_query>')).toBe('<unknown>inner</unknown>');
  });

  test('handles empty string', () => {
    expect(stripPromptWrappers('')).toBe('');
  });

  test('handles whitespace-only', () => {
    expect(stripPromptWrappers('   ')).toBe('');
  });

  test('case insensitive', () => {
    expect(stripPromptWrappers('<USER_QUERY>\nHello\n</USER_QUERY>')).toBe('Hello');
  });
});
